Mobile first work about
agneta1991/Portfolio pull request #2
Opened 2023-06-01 11:58 UTC by agneta1991

2023-06-02 14:12 UTC, shahadat3669 requested changes
Hi @agneta1991 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

It seems that there are some conflicts in your project that need to be resolved before the pull request can be successfully reviewed. It's important to address these conflicts to ensure the smooth integration of your changes into the existing codebase.

To resolve the conflicts, you can follow these steps:

1. Pull the latest changes from the main branch into your local branch.
2. Open the conflicting files in your code editor and locate the areas marked with conflict markers (<<<<<<<, =======, >>>>>>>).
3. Review the conflicting code and make the necessary changes to resolve the conflicts. You may need to choose between different code versions or manually merge the changes.
4. Save the modified files after resolving the conflicts.
5. Test your changes to ensure they work correctly and do not introduce any new issues.
6. Once you have resolved all conflicts, push the changes to your remote branch.
 
After resolving the conflicts and pushing the changes, the GitHub linter should provide a green checkmark indicating that the linter passes.

Take your time to carefully resolve the conflicts, ensuring that your changes integrate smoothly with the existing code. If you need further assistance, feel free to ask for help.

To learn more check [this document](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-02 16:15 UTC, Ofarouq310 requested changes
Hi @agneta1991, ✋ 

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/agneta1991/Portfolio/assets/102612396/c70b1574-c594-4eb9-9d89-8f9aa066e572)

## Highlights
✅ Descriptive PR title.
✅ Followed GitHub workflow.
✅ No linters errors.

## Required Changes ♻️

- [ ] As for the PR description, you have to summarize what you implemented in the project using a bullet list, a checklist, or a numbers list, in your case it could be something like:
    - Added a header section to the portfolio,
    - Added a headline section with an introduction paragraph.
    - etc...
     
or anything that has the same intent of explaining the new additions to your project.

- Your Readme file needs some attention in a couple of sections: 

  - [x] The `Contributing` section is missing the `issues` link, kindly fix it. Refer to the main [template](https://github.com/microverseinc/readme-template/blob/master/README.md) for a closer look.
  
  - [x] In The `Show Your Support` section, you should add something like `If you like this project, give me a star`, kindly fix it since what you wrote seems to be a description of your project, it seems inappropriate. Refer to the main [template](https://github.com/microverseinc/readme-template/blob/master/README.md) for a closer look.


_Check the comments under the review._

## Optional suggestions

 - Concerning commit messages, kindly make sure they should be short, concise, descriptive of an action, written in the imperative tense, and capitalized, take a closer look in the next picture for some great descriptive examples.
![image](https://github.com/obibaadoma/PotfolioMic/assets/102612396/2add25d8-4d4a-48fd-93e0-1dc1cc0c7011)

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 16:15 UTC, Ofarouq310 commented on index.html
> +            </h1>
- [ ] The whole `about` section as stated in the requirements had to be laid out using `flexbox`, kindly implement that.

2023-06-02 21:46 UTC, agneta1991 commented on index.html
> +            </section>
@shahadat3669 as i resolved the issues of my previous project in my current branch, now my pull request says there is a conflict. how can i resolve it without merging branches?

2023-06-02 21:47 UTC, agneta1991 commented
@shahadat3669 regarding PR description, i think i have mixed it up and left my description in the comment rather than description section, could you advise me how i could edit PR description?

2023-06-03 05:46 UTC, divinecharlotte approved these changes
# Hello @agneta1991     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Good design implementation👍 
- Linters are passing👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 05:49 UTC, merged